python trainer/main.py \
    --train_path feature/ESD_BERT_WAV2VEC_train.pkl \
    --valid_path feature/ESD_BERT_WAV2VEC_val.pkl \
    --test_path feature/ESD_BERT_WAV2VEC_test.pkl \
    --save_path saved_models \
    --model_name ESD_HemoGAT_mean \
    --hidden_dim 512 \
    --num_classes 5 \
    --num_layers 3 \
    --fusion_type mean \
    --epochs 100 \
    --lr 0.0001 \
    --weight_decay 0.0005 \
    --k_text 5 \
    --k_audio 4 \
    --seeds 42